### ISSUE TITLE
V3.1.12 no windows build archive + V3.1.7 for windows 4k fullscreen bug

### ISSUE THREAD

**Issue by roman80k** [projectM-visualizer/frontend-sdl2#1]
**Describe the bug**
1. There is no latest version build for Windows available
2. Latest Windows build on 4k monitor fullscreen leaves visible space at the bottom, around 50-100px.
3. Ctrl+F in this scenario crashes the application

**Screenshots**
https://snipboard.io/vVophK.jpg

**Additional context**
Scale in Windows settings is set to 200%, just in case

**Comment by kblaschke** [comment]
The rewritten app uses new code to switch between windows and fullscreen modes, and also can be configured to use either exclusive mode with resolution change, or a borderless window filling the whole screen.

There's no release yet of the new app, but this isn't considered a bug. the other issues noted in the last comment should also no longer be present in the new version, e.g. FPS limiting works and the mouse pointer is hidden in fullscreen mode and right-clicking switches between windows and fullscreen modes.

Closing this for now. If there are any issues or feature requests with the rewritten app here, please feel free to open a new issue.
