### ISSUE TITLE
projectM-sdl-win-x64 v3.1.3 hanging on Win10

### ISSUE THREAD

**Issue by chaosophy** [projectM-visualizer/frontend-sdl2#12]
Hi, just recently found this project and thought I'd give it a go but it just hangs for me.

It opens up the 'projectM Visualizer' window with a black screen and the 'M' logo in the middle but immediately goes to not responding.

The CMD window that opens just shows this...

`INFO: GL_VERSION: 3.2.13596 Core Profile Context 20.5.1 27.20.1017.1011
INFO: GL_SHADING_LANGUAGE_VERSION: 4.60
INFO: GL_VENDOR: ATI Technologies Inc.
INFO: Using data directory: /usr/local/share/projectM
INFO: Looking for configuration file in data dir: /usr/local/share/projectM.
INFO: Config file not found, using built-in settings. Data directory=D:\projectM-sdl\Release\
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
fps: 60`

I had a look but can't find any kind of config file or log file to check, also searched the web but can't really find any documentation or help for the windows version, so posting here hoping someone can help.

I've tried 3.1.3 and 3.1.2 from the release downloads, running it as admin, running it from an admin cmd.

Resource monitor shows it opens a load of handles, both registry and file handles, including files in AppData\Local\AMD\GLCache\ so at least seems to be getting that far.

Am I missing something obvious/doing something dumb?  Any way to get logs out of it to look at?

Let me know if you need any more info, h/w setup s/w versions etc.

Thanks.

**Comment by kblaschke** [comment]
The next projectM SDL release will feature a completely rewritten app, and also contain a lot of bugfixes in the underlying projectM visualizer. If the next release (in the new repo here) still exposes the described behaviour, please open a new issue.
