### ISSUE TITLE
Broken Build due to Missing References

### ISSUE THREAD

**Issue by rothn** [projectM-visualizer/frontend-sdl2#17]
Fixed by https://github.com/projectM-visualizer/frontend-sdl2/pull/16

Versions:
libprojectm: latest master (9e9f4ca1b2b767e7e35db60907b2868b096973b6)
frontend-sdl2: latest master (8200b32ba186dbfac1c7ca8d3c19c37cac5ce049)

The build is broken on master because of broken references comprising:

* Missing #includes,
* Missing linkage to various libraries, and
* Incorrect specification of linkage to projectM

**Comment by kblaschke** [comment]
As both master versions might not be compatible at all times, this can be expected. Both projects are still in heavy development and will have breaking changes. As time of writing this, both repos work and are compatible on macOS, Linux and Windows if configured and built properly.
