### ISSUE TITLE
Running ProjectM full time in background

### ISSUE THREAD

**Issue by PlaidPiper** [projectM-visualizer/frontend-sdl2#20]
My application for ProjectM (for windows) will be set as a show display inside my custom PC, and I would like it to come up on the third display automatically on startup, full screened, with a preset audio source... With as little intervention as possible. Is there a way to load startup configs in an INI or as command line parameters?

Also, is there a way to have the projectM window come up not on the taskbar? I tried to figure out a way for it to come up hidden or as a tray icon, maybe I am missing something here.

Also, is ProjectM compatible with overlays, such as rainmeter? Ideally eventually I would overlay some custom temperature readouts, cpu usage, etc on top of an active ProjectM window onto this mini display inside my rig.

Of course any of these questions, if the answer is "unsupported at this time", where is the best place to contribute to this awesome project? Do you accept donations? Patreon?

Also... Just saying..... ProjectM would make the best ever live wallpaper in windows.

**Comment by kblaschke** [comment]
I'd say running projectM as some kind of live wallpaper or background app would better be done as a separate application, as this is highly OS-specific and would probably require the use or some low-level Win32 API functions to achieve that, especially embedding it into the desktop background. Same goes for task bar appearance and a tray icon.

We currently don't have the resources in the projectM dev team to write such specialized apps. If anyone wants to take this task, feel free to contact us so we can create a repository here.
