### ISSUE TITLE
Window always opens at monitor's max res. (latest master, Win x64 build)

### ISSUE THREAD

**Issue by chaosophy** [projectM-visualizer/frontend-sdl2#3]
Hi, 

I downloaded the latest master branch and did a x64 release build for Windows using MS visual studio and projectM seems to ignore the 'Window Height' and 'Window Width settings from the 'config.inp' settings files.

The window always opens at the monitors max resolution.

If you resize the window and then ctrl+q to quit it updates the config.inp file with the new values for the window size but on re-running projectM the same thing happens and it ignores them and opens at max res.

I downloaded the 'projectm-3.1.12' release and built that the same way and it does not have this issue.

Looks like there has been a number of commits to master since the last release and my knowledge doesn't extend beyond downloading and running a build, so no idea when this happened or what might be causing it.

thanks.

**Comment by kblaschke** [comment]
The rewritten app uses the configured default size (currently 1024x768) in windowed mode when it opens. Future versions might get an option to remember the last window size, position and fullscreen setting.

Current window size is also honored when switching to exclusive fullscreen mode, which will try to set a best-match fullscreen resolution for the current window dimensions.

Closing this issue as the problem has been addressed in the rewrite. If you have suggestions on more configuration options or find there's still an issue with window management in the new app, feel free to open a new issue.
