### ISSUE TITLE
Windows - full screen command - sets a lower resolution than native

### ISSUE THREAD

**Issue by ghost** [projectM-visualizer/frontend-sdl2#4]
Hello, I am using the latest ProjectM v3.1.3
My OS is Windows 10 Enterprise, AMD video card
My display is a 4k TV, native resolution set as 3840x2160, max is 4096x2160 for some reason, I have display scaling at 175%

When I hit Ctrl+F in ProjectM, the resolution is set to 2560x1440

Is it possible to make ProjectM set the resolution that the display currently had just before, rather than look at the monitor's spec and get confused by hi-dpi monitors like this?

**Comment by kblaschke** [comment]
I'll close this issue, as at least from my tests, using the "fake" fullscreen mode in the rewritten SDL app works perfectly fine on Windows, macOS and Linux. For those who prefer the exclusive mode, there's now a configuration property to enable the old behavior and also additional values to set the wanted fullscreen resolution (the next-best resolution supported by the GPU driver is actually used).
