### ISSUE TITLE
keys or menu?

### ISSUE THREAD

**Issue by ghost** [projectM-visualizer/frontend-sdl2#50]
hi

I'm trying the frontend on windows but there are no menus.
How do I know what keys are used and is it possible to add a menu to select a preset or some other settings?
I can only go fullscreen/window mode by right clicking the window.

thx

**Comment by kblaschke** [comment]
If you're using a version from Steam, from the Windows Store or an earlier (3.x) projectM release, there's a good chance the menu is broken. Try this package here, which I built from the code in this repository and is a different application with a newer projectM core that comes with lots of bugfixes:

https://github.com/kblaschke/frontend-sdl2/releases/download/2.0-windows-pre1/projectMSDL-Windows-x64-2.0-pre1.zip

You can simply press F1 to get a help overlay with most hotkeys. Pressing enter should show a preset search menu. To change defaults, have a look in the `projectMSDL.properties` file with a text editor.

**Comment by 486DX2** [comment]
Thanks. Now everything works. For a pre-release I think it works really well. Definitely as good as original milkdrop which I used for years. I have a faster PC now so I can't compare the speed. On my PC almost 60 FPS everywhere!

Can people who don't know anything about Project M and/or programming make presets using a tool?
Or is this something for experts only?

**Comment by 486DX2** [comment]
So this version is actually the very latest project M and I can use this in combination with any audio player, right?
It listens to the audio played by any player? So I can also use it as a replacement of older Project M versions that could be use by any player?

**Comment by 486DX2** [comment]
Hi

Also the "standalone" links here are broken :(

https://github.com/projectM-visualizer/projectm

So We have to go to your own github to download it.
I think many people don't find a working download link then. Maybe they can be fixed?
It's easier to download it from official github.

**Comment by kblaschke** [comment]
> So this version is actually the very latest project M and I can use this in combination with any audio player, right?
> It listens to the audio played by any player? So I can also use it as a replacement of older Project M versions that could be use by any player?

Basically yes. It uses your default audio output device and records it to turn it into visuals. You can press ctrl-i to toggle between all available playback or input devices.

We know about the link issue, it's probably better to remove them for now. The pre-release works well for sure, but isn't an official, production-ready release. Especially the core API is still being changed frequently, which can be exhausting for developers to follow if they expect it to be stable.

**Comment by selurvedu** [comment]
> You can simply press F1 to get a help overlay with most hotkeys

This was removed in 620e259f33bf7ae75efb1d0105e8a49ebedb74ed. Some hotkey info in the README could help while there's no overlay.

**Comment by kblaschke** [comment]
There are only dev releases in the meantime, the next release will come with both a new UI and updated documentation. Otherwise, the (old) keyboard shortcuts are documented in the projectM main Wiki, to which the SDL frontend previously belonged:

https://github.com/projectM-visualizer/projectm/wiki/User-Manual-(Standalone,-v3.1.x)#hotkey-reference

**Comment by kblaschke** [comment]
The initial UI code has just been merged. There's still stuff missing, like a preset playlist editor and a search function, but settings and a help dialog are there.

Press ESC to toggle the UI.
