### ISSUE TITLE
No config, no keybinds

### ISSUE THREAD

**Issue by Leuphorie** [projectM-visualizer/frontend-sdl2#7]
Trying to use the projectM sdl Windows build

INFO: GL_VERSION: 3.2.0 NVIDIA 391.01
INFO: GL_SHADING_LANGUAGE_VERSION: 1.50 NVIDIA via Cg compiler
INFO: GL_VENDOR: NVIDIA Corporation
INFO: Config file not found, using development settings
[PresetFactory] url is idle://Geiss & Sperl - Feedback (projectM idle HDR mix).milk
No Textures Loaded from ./textures
No Textures Loaded from ./textures
INFO: Using audio driver: wasapi
INFO: Found audio capture device 0: Stereo Mix (Realtek High Definition Audio)
INFO: Found audio capture device 1: Microphone (Logitech G430 Gaming Headset)
Detected devices:
  0: 痔Stereo Mix (Realtek High Definition Audio)
  1: 痔Microphone (Logitech G430 Gaming Headset)
INFO: Opened audio capture device 2: Stereo Mix (Realtek High Definition Audio)
INFO: Sample rate: 512, frequency: 48000, channels: 2, format: 33056
fps: 60

**Comment by kblaschke** [comment]
Closing this issue as none of the original code is present in the rewritten app. Config file handling is completely different and the build system will make sure that a default config is installed alongside the executable, while the user can still override any default values with a custom config file in `%APPDATA%\projectMSDL` on Windows (or `${XDG_CONFIG_HOME}/projectMSDL` on Linux).
