### ISSUE TITLE
Customizable keybindings

### ISSUE THREAD

**Issue by EvanCarroll** [projectM-visualizer/frontend-sdl2#9]
I know this is somewhat petty, but I would love to have Vim-esque keybindings

* <kbd>H</kbd> previous
* <kbd>L</kbd> next
* <kbd>space</kbd> play/pause (lock)
* <kbd>S</kbd> shuffle
* <kbd>F11</kbd> maximize 
* <kbd>I</kbd> (instead of <kbd>Ctrl</kbd> + <kbd>B</kbd>)

----

<kbd>Ctrl</kbd> + <kbd>R</kbd>, <kbd>M</kbd> would be great without <kbd>Ctrl</kbd>

----
<kbd>Ctrl</kbd>+<kbd>S</kbd> and <kbd>Ctrl</kbd>+<kbd>E</kbd> make sense to me as is.

----

I wouldn't push something like this hard, but it just seems like that would make it a lot more natural for those of geeks that use with lot of other stuff. Right now I'm running i3 (vim), tmux (vim), vim (vim), ranger (vim), and vlc (vim).

**Comment by kblaschke** [comment]
This is already under consideration as a feature when this app will receive a new UI (basd on Dear ImGui) with settings and playlist management dialogs. This will make editing key bindings less cumbersome, as doing this in a config file is not really user-friendly.

**Comment by kblaschke** [comment]
closing as duplicate of issue #8.
